export const GET_ALL_PROJECTS_REQUEST = 'GET_ALL_PROJECTS_REQUEST' as const;
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS' as const;
export const GET_ALL_PROJECTS_FAILURE = 'GET_ALL_PROJECTS_FAILURE' as const;

export const ADD_NEW_PROJECT_REQUEST = 'ADD_NEW_PROJECT_REQUEST' as const;
export const ADD_NEW_PROJECT_SUCCESS = 'ADD_NEW_PROJECT_SUCCESS' as const;
export const ADD_NEW_PROJECT_FAILURE = 'ADD_NEW_PROJECT_FAILURE' as const;

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST' as const;
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS' as const;
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE' as const;

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST' as const;
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS' as const;
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE' as const;
