export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST' as const;
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS' as const;
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE' as const;
